---
title: "wordcloud"
author: "Jack Schloesser"
date: "2026-04-29"
output: html_document
---

```{r}
library(wordcloud)
library(RColorBrewer)
library(dplyr)
library(tm)
```

```{r}
word_counts <- word_df %>%
  count(word, sort = TRUE)

word_counts_filtered <- word_counts %>% #filters out words with less than 5 occurences
  filter(n >= 5)

word_counts_filtered <- word_counts %>% #filters out common words (the, a, etc.)
  filter(n >= 5) %>%
  filter(!word %in% stopwords("en"))

set.seed(123)

decades <- unique(word_df$decade)

for (dec in decades) {
  
  # Filter data for this decade
  df_subset <- word_df %>%
    filter(decade == dec)
  
  # Count words and filter
  word_counts <- df_subset %>%
    count(word, sort = TRUE) %>%
    filter(n >= 5) %>%
    filter(!word %in% stopwords("en"))
  
  # Create word cloud
  wordcloud(
    words = word_counts$word,
    freq = word_counts$n,
    min.freq = 5,
    max.words = 200,
    random.order = FALSE,
    rot.per = 0.35,
    colors = brewer.pal(8, "Dark2")
  )
  
  # Add title
  title(paste("Word Cloud -", dec))
}
```